### ISSUE TITLE
cannot create index in elasticsearch-1.6.0 with mmseg plugin installed.

### ISSUE THREAD

**Issue by foresightyj** [medcl/elasticsearch-analysis-mmseg#13]
I used the mmseg plugin with elasticsearch-1.5.2 for the past few months without any problems. I upgraded to elasticsearch-1.6.0 and now I have a problem with mmseg plugin.

    PUT /blogs
    {
      "settings": {
        "number_of_shards": 3,
        "number_of_replicas": 1
      }
    }

    {
       "error": "IndexCreationException[[blogs] failed to create index]; nested: NullPointerException; ",
       "status": 500
    }

Here is the exception in elasticsearch.log:

    [2015-07-02 16:55:20,603][DEBUG][action.admin.indices.create] [Micro] [blogs] failed to create
    org.elasticsearch.indices.IndexCreationException: [blogs] failed to create index
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:338)
        at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:371)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:188)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:158)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NullPointerException
        at com.chenlb.mmseg4j.Dictionary.loadDic(Dictionary.java:160)
        at com.chenlb.mmseg4j.Dictionary.reload(Dictionary.java:364)
        at com.chenlb.mmseg4j.Dictionary.init(Dictionary.java:130)
        at com.chenlb.mmseg4j.Dictionary.<init>(Dictionary.java:123)
        at com.chenlb.mmseg4j.Dictionary.getInstance(Dictionary.java:74)
        at com.chenlb.mmseg4j.Dictionary.getInstance(Dictionary.java:63)
        at org.elasticsearch.index.analysis.MMsegTokenizerFactory.<init>(MMsegTokenizerFactory.java:31)
        at sun.reflect.GeneratedConstructorAccessor8.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
        at org.elasticsearch.common.inject.InjectorImpl$5$1.call(InjectorImpl.java:781)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.InjectorImpl$5.get(InjectorImpl.java:777)
        at org.elasticsearch.common.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:221)
        at com.sun.proxy.$Proxy16.create(Unknown Source)
        at org.elasticsearch.index.analysis.AnalysisService.<init>(AnalysisService.java:82)
        at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:54)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at org.elasticsearch.common.inject.SingleParameterInjector.getAll(SingleParameterInjector.java:66)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:98)
        at org.elasticsearch.common.inject.FactoryProxy.get(FactoryProxy.java:52)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:837)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:57)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:830)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:193)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:175)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:110)
        at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
        at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:336)
        ... 7 more

Hope you can take a look at the problem. Thanks again for the great plugin!

**Comment by medcl** [comment]
我刚试了没有问题啊,你的mmseg是重新编译的么?

**Comment by xguox** [comment]
同样遇上这个问题, 也是es-1.6.0

https://github.com/medcl/elasticsearch-rtf/tree/master/plugins/analysis-mmseg 这里下载的 jar
![image](https://cloud.githubusercontent.com/assets/1177920/8480926/1a9ebeb8-2113-11e5-8a25-c10f9cddaf96.png)

以及字典 https://github.com/medcl/elasticsearch-rtf/tree/master/config/mmseg

![image](https://cloud.githubusercontent.com/assets/1177920/8480963/591ec1b0-2113-11e5-908f-489ce56f4f53.png)

配置文件 elasticsearch.yml
![image](https://cloud.githubusercontent.com/assets/1177920/8481014/9567809e-2113-11e5-843e-be8139318d8f.png)

**Comment by foresightyj** [comment]
没有编译，我是运行在Windows 7 上面的。
每次都是到https://github.com/medcl/elasticsearch-rtf里面将mmseg的那个文件夹移到plugin的。
之前的版本没有问题。难道要每次重新编译？
我没有怎么搞过java，那我试试。不过我没有怎么搞过java，估计要花点时间试试。

**Comment by medcl** [comment]
请从分支1.6.0下面下载jar包.

**Comment by xguox** [comment]
换了, 重新 load 过 elasticsearch, 还是一样的问题 
![image](https://cloud.githubusercontent.com/assets/1177920/8491663/0da960ca-2170-11e5-82d1-e7b1f3153e6f.png)

**Comment by xguox** [comment]
OK 了, 我的错. 我多加了一层 config 目录

**Comment by medcl** [comment]
配置文件发我,测试流程发我.

**Comment by xguox** [comment]
我这边 OK 了, 谢谢

**Comment by foresightyj** [comment]
突然发现我也搞了个乌龙。我原来是忘了拷贝elasticsearch-1.6.0\config里面对应的mmseg的文件夹，只记得拷贝plugins里面的了。我说之前elasticsearch-1.5.2没有问题，是因为我作为副本的elasticsearch-1.5.2里面的config里面一直保留mmseg文件夹。

所以本来没有bug。不好意思，浪费你时间了。

**Comment by baiyuang** [comment]
什么时候解决CutLetterDigitFilter这个过滤器的问题？

**Comment by medcl** [comment]
already fix,issue cleared
