### ISSUE TITLE
请教关于安装mmseg插件的一些问题

### ISSUE THREAD

**Issue by wefound** [medcl/elasticsearch-analysis-mmseg#15]
# 系统信息
* Linux MyCentOS 2.6.32-431.23.3.el6.x86_64 \#1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
* 4核8G

# 安装过程

下载elasticsearch的rpm包安装，版本为1.7.2，jdk是通过yum安装，版本为1.8
```
./elasticsearch -v
Version: 1.7.2, Build: e43676b/2015-09-14T09:49:53Z, JVM: 1.8.0_51
```

从elasticsearch-rtf的1.7.1分支中下载了```plugins/mmseg/elasticsearch-analysis-mmseg-1.4.0.jar```放到```/usr/share/elasticsearch/plugins/mmseg/elasticsearch-analysis-mmseg-1.4.0.jar```下的对应目录
```bash
.
├── bin
│   ├── elasticsearch
│   ├── elasticsearch.in.sh
│   └── plugin
├── lib
│   ├── antlr-runtime-3.5.jar
│   ├── apache-log4j-extras-1.2.17.jar
│   ├── asm-4.1.jar
│   ├── asm-commons-4.1.jar
│   ├── elasticsearch-1.7.2.jar
│   ├── groovy-all-2.4.4.jar
│   ├── jna-4.1.0.jar
│   ├── jts-1.13.jar
│   ├── log4j-1.2.17.jar
│   ├── lucene-analyzers-common-4.10.4.jar
│   ├── lucene-core-4.10.4.jar
│   ├── lucene-expressions-4.10.4.jar
│   ├── lucene-grouping-4.10.4.jar
│   ├── lucene-highlighter-4.10.4.jar
│   ├── lucene-join-4.10.4.jar
│   ├── lucene-memory-4.10.4.jar
│   ├── lucene-misc-4.10.4.jar
│   ├── lucene-queries-4.10.4.jar
│   ├── lucene-queryparser-4.10.4.jar
│   ├── lucene-sandbox-4.10.4.jar
│   ├── lucene-spatial-4.10.4.jar
│   ├── lucene-suggest-4.10.4.jar
│   ├── sigar
│   │   ├── libsigar-amd64-linux.so
│   │   ├── libsigar-ia64-linux.so
│   │   ├── libsigar-x86-linux.so
│   │   └── sigar-1.6.4.jar
│   └── spatial4j-0.4.1.jar
├── LICENSE.txt
├── NOTICE.txt
├── plugins
│   └── analysis-mmseg
│       └── elasticsearch-analysis-ik-1.4.0.jar
└── README.textile

```
从elasticsearch-rtf的1.7.1分支中下载了```config/mmseg```放到了```/etc/elasticsearch/config/mmseg```
``` bash
/etc/elasticsearch/
├── elasticsearch.yml
├── logging.yml
└── mmseg
    ├── chars.dic
    ├── units.dic
    ├── words.dic
    └── words-my.dic

1 directory, 6 files
```

在/etc/elasticsearch/elasticsearch.conf的最后面，参考 https://github.com/medcl/elasticsearch-analysis-mmseg 添加了
``` bash
#for chinese
index:
  analysis:
    analyzer:
      mmseg:
        alias: [news_analyzer, mmseg_analyzer]
        type: org.elasticsearch.index.analysis.MMsegAnalyzerProvider
index.analysis.analyzer.default.type : "mmseg"
```
重启服务：
```
service elasticsearch restart
Stopping elasticsearch:                                    [  OK  ]
Starting elasticsearch:                                    [  OK  ]

curl  http://localhost:9200
{
  "status" : 200,
  "name" : "node-0",
  "cluster_name" : "search-srv",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}



```
尝试创建index
``` bash
curl -XPUT http://localhost:9200/myindex
```
返回结果如下
```
{
    "error":"IndexCreationException[[myindex] failed to create index]; 
nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [mmseg] or tokenizer for [mmseg]]; 
nested: NoClassSettingsException[Failed to load class setting [type] with value [mmseg]]; 
nested: ClassNotFoundException[org.elasticsearch.index.analysis.mmseg.MmsegAnalyzerProvider]; ",
    "status":400
}
```
服务的启动日志，没加载插件？怎么配置才能加载上？
@medcl 
```
[2015-09-23 23:52:13,740][INFO ][node                     ] [node-0] stopping ...
[2015-09-23 23:52:13,762][INFO ][node                     ] [node-0] stopped
[2015-09-23 23:52:13,762][INFO ][node                     ] [node-0] closing ...
[2015-09-23 23:52:13,769][INFO ][node                     ] [node-0] closed
[2015-09-23 23:52:14,353][INFO ][node                     ] [node-0] version[1.7.2], pid[5814], build[e43676b/2015-09-14T09:49:53Z]
[2015-09-23 23:52:14,354][INFO ][node                     ] [node-0] initializing ...
[2015-09-23 23:52:14,436][INFO ][plugins                  ] [node-0] loaded [], sites []
.......................sth............................
[2015-09-23 23:53:06,285][DEBUG][action.admin.indices.create] [node-0] [myindex] failed to create
org.elasticsearch.indices.IndexCreationException: [myindex] failed to create index
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:338)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$2.execute(MetaDataCreateIndexService.java:371)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:204)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:167)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: failed to find analyzer type [mmseg] or tokenizer for [mmseg]
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:372)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:204)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:85)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:130)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.InjectorImpl.createChildInjector(InjectorImpl.java:131)
	at org.elasticsearch.common.inject.ModulesBuilder.createChildInjector(ModulesBuilder.java:69)
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:336)
	... 7 more
Caused by: org.elasticsearch.common.settings.NoClassSettingsException: Failed to load class setting [type] with value [mmseg]
	at org.elasticsearch.common.settings.ImmutableSettings.loadClass(ImmutableSettings.java:476)
	at org.elasticsearch.common.settings.ImmutableSettings.getAsClass(ImmutableSettings.java:464)
	at org.elasticsearch.index.analysis.AnalysisModule.configure(AnalysisModule.java:356)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.analysis.mmseg.MmsegAnalyzerProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

```
但是执行plugin工具
```bash
plugin -l
Installed plugins:
    - analysis-mmseg
```

请问是不是我哪里少了一步？配置问题？版本问题？or安装问题？求解~

**Comment by medcl** [comment]
试过手动编译插件的jar包么,修改下es版本,尽量保证es和插件的es是相同版本

**Comment by wefound** [comment]
@medcl 多谢，手动编译后通过了。
