### ISSUE TITLE
can not read dictionary when start up Elasticsearch. 

### ISSUE THREAD

**Issue by lxWei** [medcl/elasticsearch-analysis-mmseg#32]
Can not start up Elasticsearch and the message is:

`org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.plugin.analysis.mmseg.AnalysisMMsegPlugin]]; nested: InvocationTargetException; nested: NullPointerException;
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.cli.Command.main(Command.java:62) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.0.2.jar:5.0.2]
Caused by: org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.elasticsearch.plugin.analysis.mmseg.AnalysisMMsegPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:462) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:414) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 6 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:454) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:414) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 6 more
Caused by: java.lang.NullPointerException
	at com.chenlb.mmseg4j.Dictionary.loadDic(Dictionary.java:163) ~[?:?]
	at com.chenlb.mmseg4j.Dictionary.reload(Dictionary.java:367) ~[?:?]
	at com.chenlb.mmseg4j.Dictionary.init(Dictionary.java:133) ~[?:?]
	at com.chenlb.mmseg4j.Dictionary.<init>(Dictionary.java:45) ~[?:?]
	at com.chenlb.mmseg4j.Dictionary.getInstance(Dictionary.java:84) ~[?:?]
	at com.chenlb.mmseg4j.Dictionary.getInstance(Dictionary.java:67) ~[?:?]
	at org.elasticsearch.plugin.analysis.mmseg.AnalysisMMsegPlugin.<init>(AnalysisMMsegPlugin.java:35) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:454) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:414) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:144) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.node.Node.<init>(Node.java:217) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:196) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:291) ~[elasticsearch-5.0.2.jar:5.0.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.0.2.jar:5.0.2]
	... 6 more`

I checked the source code and found the method getDictRoot() in Class Dictionary get the wrong path. So I used getDefalutPath() and pass the dictionary path through `-Dmmseg.dic.path="$MMSEG_DICT_PATH"`. It works.

**Comment by medcl** [comment]
just drop the plugin to es's plugin folder, nothing needed

**Comment by medcl** [comment]
can you

**Comment by Hellowshuo** [comment]
我出现了和他一样的问题，但是我没明白你说的把插件放到es的插件文件夹的意思，能详细说一遍吗？谢谢
