### ISSUE TITLE
ElasticSearchIllegalArgumentException[failed to find analyzer [mmseg]]

### ISSUE THREAD

**Issue by chrisyue** [medcl/elasticsearch-analysis-mmseg#6]
我按你说的将rtf版本的mmseg及其配置文件都cp到相应的位置

从日志上看已经成功加载plugin以及词典文件

但是执行分析器测试的时候就是找不到analyzer，我按装了mmseg，ik，pinyin，都是这样

这是启动的日志：

```
[2013-05-31 01:33:23,058][INFO ][node                     ] [Tarot] {0.90.0}[15503]: initializing ...
[2013-05-31 01:33:23,079][INFO ][plugins                  ] [Tarot] loaded [analysis-mmseg, analysis-pinyin, analysis-ik], sites [head]
[2013-05-31 01:33:25,599][INFO ][node                     ] [Tarot] {0.90.0}[15503]: initialized
[2013-05-31 01:33:25,600][INFO ][node                     ] [Tarot] {0.90.0}[15503]: starting ...
[2013-05-31 01:33:25,717][INFO ][transport                ] [Tarot] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/192.168.1.105:9300]}
[2013-05-31 01:33:28,808][INFO ][cluster.service          ] [Tarot] new_master [Tarot][QyqG17rTTzuaIZvhOMvBNw][inet[/192.168.1.105:9300]], reason: zen-disco-join (elected_as_master)
[2013-05-31 01:33:28,864][INFO ][discovery                ] [Tarot] elasticsearch/QyqG17rTTzuaIZvhOMvBNw
[2013-05-31 01:33:28,885][INFO ][http                     ] [Tarot] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/192.168.1.105:9200]}
[2013-05-31 01:33:28,885][INFO ][node                     ] [Tarot] {0.90.0}[15503]: started
[2013-05-31 01:33:29,187][INFO ][index.analysis           ] [Tarot] [dls] /etc/elasticsearch/mmseg
[2013-05-31 01:33:29,371][INFO ][com.chenlb.mmseg4j.Dictionary] chars loaded time=182ms, line=12638, on file=/etc/elasticsearch/mmseg/chars.dic
[2013-05-31 01:33:29,375][INFO ][com.chenlb.mmseg4j.Dictionary] words loaded time=1ms, line=1, on file=/etc/elasticsearch/mmseg/words-my.dic
[2013-05-31 01:33:29,576][INFO ][com.chenlb.mmseg4j.Dictionary] words loaded time=201ms, line=157202, on file=/etc/elasticsearch/mmseg/words.dic
[2013-05-31 01:33:29,576][INFO ][com.chenlb.mmseg4j.Dictionary] load all dic use time=387ms
[2013-05-31 01:33:29,577][INFO ][com.chenlb.mmseg4j.Dictionary] unit loaded time=1ms, line=22, on file=/etc/elasticsearch/mmseg/units.dic
[2013-05-31 01:33:29,579][INFO ][index.analysis           ] [Tarot] [dls] /etc/elasticsearch/mmseg
[2013-05-31 01:33:29,584][INFO ][index.analysis           ] [Tarot] [dls] /etc/elasticsearch/mmseg
[2013-05-31 01:33:29,586][INFO ][index.analysis           ] [Tarot] [dls] /etc/elasticsearch/mmseg
[2013-05-31 01:33:29,664][INFO ][ik-analyzer              ] [Dict Loading] ik/IKAnalyzer.cfg.xml
[2013-05-31 01:33:30,460][INFO ][ik-analyzer              ] 加载扩展词典：ik/custom/mydict.dic
[2013-05-31 01:33:30,461][INFO ][ik-analyzer              ] 加载扩展停止词典：ik/custom/ext_stopword.dic
[2013-05-31 01:33:31,211][INFO ][gateway                  ] [Tarot] recovered [1] indices into cluster_state
```

这是找不到analyzer时的日志

```
[2013-05-31 01:34:08,970][DEBUG][action.admin.indices.analyze] [Tarot] failed to execute [org.elasticsearch.action.admin.indices.analyze.AnalyzeRequest@32b9bd47]
org.elasticsearch.ElasticSearchIllegalArgumentException: failed to find analyzer [mmseg]
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:147)
    at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:57)
    at org.elasticsearch.action.support.single.custom.TransportSingleCustomOperationAction$AsyncSingleAction$1.run(TransportSingleCustomOperationAction.java:142)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by iwwenbo** [comment]
@chrisyue 请问你知道如何不指定索引Index 怎么分词查询了吗
